
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nprdcdhehmrlndmrmtbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wcmRjZGhlaG1ybG5kbXJtdGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODQyODgsImV4cCI6MjA2MTY2MDI4OH0.BLryZpIaW0u3xhC1TZnyxoClinXIumntvsKuQ75Bq-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add a helper function to get typed references to tables
// This is a workaround for TypeScript errors with Supabase types
export const getTypedTable = <T extends keyof Database['public']['Tables']>(
  tableName: T
) => {
  return supabase.from(tableName);
};
