// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdugalhraxbcfxbsevfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkdWdhbGhyYXhiY2Z4YnNldmZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMjcxMTUsImV4cCI6MjA1NjkwMzExNX0.7Qc9OqHByXq4N70_oJRlyPuaT3438ALUgbAOMWv99-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);