// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiuielaouuipgeqgghgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpdWllbGFvdXVpcGdlcWdnaGdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjY5ODMsImV4cCI6MjA2MTM0Mjk4M30.2ZyJbJ9lprB5mDz2M_-V8pS5QrMoPCOr1-nQGxkSIjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);